### ISSUE TITLE
.otf support?

### ISSUE THREAD

**Issue by ghost** [charityrolfson433/mffmv11#1]
Hi! I followed all the steps in the README, the module successfully installs but the font does not change upon reboot..

The only difference between the README and what I did was use .otf files for my font instead of .ttf

Are .otf font files supported? Thanks!

**Comment by jay-ramani** [comment]
As far as I know, Android only supports TTF, but I read somewhere on one of the forums on XDA that all one has to do is rename OTF to TTF, and Android would still recognize the font.

Try it, and let all know if that works.

Cheers.
